### ISSUE TITLE
Conflict in namespaces DODP and Bookmarks

### ISSUE THREAD

**Issue by fredrikschill** [daisy/DAISY-Online-Refresh#42]
**Origin**
[Conflict in namespaces DODP and Bookmarks] (https://github.com/daisy/DAISY-Online-Refresh/wiki/DODPRequirementsAnalysis#Conflict_in_namespaces_DODP_and_Bookmarks)

**What**
Generating code from the current WSDL may result in conflict with type names from different namespaces. Include a known issues section in the documentation and provide work arounds for them if possible.

**Why**
There is a conflict between audio types from the DODP namespace and the bookmarkSet namespace.

**Notes/Comments**

### Issue

At Kolibre we had problems with this conflict for both our service and client. When we generated code from the WSDL, the code generator would first create a model of object types based on the name of the type defined in the schema, without namespaces taken into account. Since labels and boomarks both may contain an audio object (of different types) the generator would assume (in our case, since the bookmark object was created after the label object) that the audio object in bookmarks is the same as the audio object in labels.

### Work around

To work around this issue, we renamed the audio type in the bookmarkSet namespace to bookmarkAudio.

Additionally we had to patch the generated code so that bookmarkAudio objects were not serialized with name "bookmarkAudio" but instead as "audio" in the SOAP body. And equally during the de-serialization of incoming request, we had to patch to generated code to not expect types of name "bookmarkAudio" but instead "audio".

### How

A solution would be to rename the audio type in the DODP specification to xxx.

Renaming the audio type may cause extra work for others, especially if code generators are not used. We don't expect that the a rename will occur but we urge that similar conflicts are avoided when new types in the DODP namespace are introduced.

**Comment by DaveGunn** [comment]
The working group agreed on that we would test the current code generators for namespace conflicts.
