### ISSUE TITLE
EPUB3 Support

### ISSUE THREAD

**Issue by cmontalban** [daisy/DAISY-Online-Refresh#46]
Include in the documentation method for distributing EPUB3 using DODP.

**Comment by DaveGunn** [comment]
Discussed in meetings:
https://github.com/daisy/DAISY-Online-Refresh/wiki/Minutes-of-the-call-5-January-2015
https://github.com/daisy/DAISY-Online-Refresh/wiki/Minutes-of-the-call-12-January-2015
Which concluded that the protocol supports the transfer of any file format, including EPUB3, and that while it may be helpful to highlight the support in the guidance documentation, no specific entries were required in the protocol.
