### ISSUE TITLE
Feedback: 3.1.4. HTTP Range Headers

### ISSUE THREAD

**Issue by DaveGunn** [daisy/DAISY-Online-Refresh#50]
Feedback from Solutions Radio:
3.1.4. HTTP Range Headers
"As it is not possible to require support for range headers on Service Delegates, Reading Systems must be able to handle servers that do not support range headers."

Range requests should always be handled by the service. If not then correct streaming support is not possible, It will also hamper downloads. (eg they are not able to resume)
Note that it is very unlikely that any service delegate will not support range request.

**Comment by giltay** [comment]
"Service Delegate" specifically means that the service provider does not have control over the content or delivery mechanisms, such as a partner organization, or even a public repository. In other words, the service provider cannot *require* the other service to provide full support for range requests.

There are a few options to deal with this:
a) Change the language of the requirement such that "handling" a non-compliant server includes providing reduced functionality or none at all and rendering an error message.
b) Remove any requirement of "handling", but leave a warning in the documentation that Content hosted by Service Delegates may not have range header support and leave it to developers .
c) Require that Service Providers only use Service Delegates that do support range headers.
d) Disallow Service Delegates entirely; remove it from the protocol. (Is there anyone actually providing access to another organization's resources in this way? Or planning to?)

**Comment by cmontalban** [comment]
We will make a recommendation to include HTTP range headers and explain without it streaming service is not possible and downloading experience will be affected if there are drop outs.
