### ISSUE TITLE
Vision Australia Feedback

### ISSUE THREAD

**Issue by cmontalban** [daisy/DAISY-Online-Refresh#52]
* **REQ7:** Time framed content delivery
We currently have methodHint we propose this is renamed to accessType for better clarity, (download, Stream) and priorityHint (Low, Medium, High)
We believe there are only 3 valid cases:
Steaming/High
Download/High
Download/Low/background
This can be modelled in a single attribute (eg Background, Download, and Stream) rather than the current 2.

**Recommendation:** Remove priorityHint and change the accessType to contain the possible values: Background, Download or Stream

* **REQ15:** Reduced function call sequence for building a Bookshelf.
We could merge metadata, contentMetadata with ContentItem - the metadata and contentMetadata are not used by any other methods and appear to have a 1-1 mandatory relationship.

**Recommendation:** We merge the contentItem and contentMetadata leaving the metadata element as it is.

* **REQ11:** Restrict user access to expired content (online)
returnBy date is specified as UTC. Should all dates be specified as UTC?

**Recommendation:** lastModifiedDate, firstAccessedDate, lastAccessedDate to be made in UTC
Assumption is that the Player is able to localise Date/Time to display to the user.

* **REQ31:** 302 Moved Temporarily
This looks like it is only retained in HTTP1.1 for compatibility reasons and should possible be using 307. Do we need to document the process of returning from a Temp move?

**Recommendation:** Use HTTP1.1 code 307 and write guidance on process to return from a temporary move.

* **REQ19:** Review modelling of ```<Resources>```. Currently Zip file attributes are duplicated; this could be modelled so a Zip type existed with Zip attributes, and then contained within it 1 or more resource elements.

**Current format:**

	```<resources xmlns="http://www.daisy.org/ns/daisy-online/">
	   <resource mimeType="text/xml" size="123456" 
	    uri="https://example.com/content/get.php?a123891"
	    localURI="package.opf"
	    packageURI="https://example.com/content/get.php?123"
	    packageMimeType="application/zip"
	    packageSize="987"/>
	  <resource mimeType="application/x-dtbncx+xml" size="123456" 
	    uri="https://example.com/content/get.php?a123892"
	    localURI="nav.ncx"
	    packageURI="https://example.com/content/get.php?123"
	    packageMimeType="application/zip"
	    packageSize="987"/>
	  <resource mimeType="application/smil" size="567890" 
	    uri="https://example.com/content/get.php?a123893"
	    localURI="chapter_1.smil"
	    packageURI="https://example.com/content/get.php?123"
	    packageMimeType="application/zip"
	    packageSize="987"/>
	  <resource mimeType="audio/mpeg" size="123456789" 
	    uri="https://example.com/content/get.php?a123894"
	    localURI="chapter_1.mp3"/>
	  <resource mimeType="image/jpeg" size="23456"
	</resources>``` 
	
**Proposed Format:**	
	
	```<resources xmlns="http://www.daisy.org/ns/daisy-online/">
	   <package URI="https://example.com/content/get.php?123"
	    MimeType="application/zip"
	    Size="987">
	       <resource mimeType="text/xml" size="123456" 
	       uri="https://example.com/content/get.php?a123891"
	       localURI="package.opf"/>
	       <resource mimeType="application/x-dtbncx+xml" size="123456" 
	       uri="https://example.com/content/get.php?a123892"
	       localURI="nav.ncx"/>
	     <resource mimeType="application/smil" size="567890" 
	       uri="https://example.com/content/get.php?a123893"
	       localURI="chapter_1.smil"/>
	  </package>
	  <resource mimeType="audio/mpeg" size="123456789" 
	    uri="https://example.com/content/get.php?a123894"
	    localURI="chapter_1.mp3"/>
	</resources>```

**Recommendation:** Model Packaged Resources using the proposed format.

* **REQ19**: We have an element named supportsResourcePackages to define if Zip files (partial or Full) are supported. But this could be achieved simply by setting a contentFormat in ReadingsystemAttrributes of application/zip which is required anyway. The attributes supportsResourcePackages seems redundant.

**Recommendation:** Remove the attribute supportsResourcePackages

* **Service Models Section** 
Do we really need it?
Does it make any difference to a person implementing either a Service or Reading System?
This seems to be irrelevant in the light of the removal of RequiresReturn, there is no current differentiation between Lending model and Purchasing model, and many Services use both models.

**Recommendation:** Remove Service Models Section from the protocol.

* **Review of Optional vs Required methods** 
Should addContentToBookshelf be optional?
For example a Library manages its own content allocation and does not support the loaning of Content via the Service.

**Recommendation:** addContentToBookshelf be made optional

**Comment by jmkok** [comment]
> REQ11: Restrict user access to expired content (online) returnBy date 
is specified as UTC. Should all dates be specified as UTC?

No. The data type for the returnBy and lastModifiedDate functions are 
"xs:dateTime"
The "xs:dateTime" are timezone aware (see: 
http://www.w3schools.com/schema/schema_dtypes_date.asp)
One of the "ideas" was that changing a reading systems timezone might 
bypass security. This is NOT true.
It merely changes the (human) presentation, but does not change the time 
itself.

examples
2002-05-30T09:30:10-06:00
changing the timezone:
2002-05-30T07:30:10-08:00

Jelle Martijn

On 16-02-15 15:30, Claudio wrote:
>
>   * *REQ7:* Time framed content delivery We currently have methodHint
>     we propose this is renamed to accessType for better clarity,
>     (download, Stream) and priorityHint (Low, Medium, High) We believe
>     there are only 3 valid cases: Steaming/High Download/High
>     Download/Low/background This can be modelled in a single attribute
>     (eg Background, Download, and Stream) rather than the current 2.
>
> *Recommendation:* Remove priorityHint and change the accessType to 
> contain the possible values: Background, Download or Stream
>
>   * *REQ15:* Reduced function call sequence for building a Bookshelf.
>     We could merge metadata, contentMetadata with ContentItem - the
>     metadata and contentMetadata are not used by any other methods and
>     appear to have a 1-1 mandatory relationship.
>
> *Recommendation:* We merge the contentItem and contentMetadata leaving 
> the metadata element as it is.
>
>   * *REQ11:* Restrict user access to expired content (online) returnBy
>     date is specified as UTC. Should all dates be specified as UTC?
>
> *Recommendation:* lastModifiedDate, firstAccessedDate, 
> lastAccessedDate to be made in UTC
> Assumption is that the Player is able to localise Date/Time to display 
> to the user.
>
>   * *REQ31:* 302 Moved Temporarily This looks like it is only retained
>     in HTTP1.1 for compatibility reasons and should possible be using
>     307. Do we need to document the process of returning from a Temp move?
>
> *Recommendation:* Use HTTP1.1 code 307 and write guidance on process 
> to return from a temporary move.
>
>   * *REQ19:* Review modelling of |<Resources>|. Currently Zip file
>     attributes are duplicated; this could be modelled so a Zip type
>     existed with Zip attributes, and then contained within it 1 or
>     more resource elements.
>
> *Current format:*
>
> |```<resources xmlns="http://www.daisy.org/ns/daisy-online/">
>     <resource mimeType="text/xml" size="123456"
>      uri="https://example.com/content/get.php?a123891"
>      localURI="package.opf"
>      packageURI="https://example.com/content/get.php?123"
>      packageMimeType="application/zip"
>      packageSize="987"/>
>    <resource mimeType="application/x-dtbncx+xml" size="123456"
>      uri="https://example.com/content/get.php?a123892"
>      localURI="nav.ncx"
>      packageURI="https://example.com/content/get.php?123"
>      packageMimeType="application/zip"
>      packageSize="987"/>
>    <resource mimeType="application/smil" size="567890"
>      uri="https://example.com/content/get.php?a123893"
>      localURI="chapter_1.smil"
>      packageURI="https://example.com/content/get.php?123"
>      packageMimeType="application/zip"
>      packageSize="987"/>
>    <resource mimeType="audio/mpeg" size="123456789"
>      uri="https://example.com/content/get.php?a123894"
>      localURI="chapter_1.mp3"/>
>    <resource mimeType="image/jpeg" size="23456"
> </resources>```
> |
>
> *Proposed Format:*
>
> |```<resources xmlns="http://www.daisy.org/ns/daisy-online/">
>     <package URI="https://example.com/content/get.php?123"
>      MimeType="application/zip"
>      Size="987">
>         <resource mimeType="text/xml" size="123456"
>         uri="https://example.com/content/get.php?a123891"
>         localURI="package.opf"/>
>         <resource mimeType="application/x-dtbncx+xml" size="123456"
>         uri="https://example.com/content/get.php?a123892"
>         localURI="nav.ncx"/>
>       <resource mimeType="application/smil" size="567890"
>         uri="https://example.com/content/get.php?a123893"
>         localURI="chapter_1.smil"/>
>    </package>
>    <resource mimeType="audio/mpeg" size="123456789"
>      uri="https://example.com/content/get.php?a123894"
>      localURI="chapter_1.mp3"/>
> </resources>```
> |
>
> *Recommendation:* Model Packaged Resources using the proposed format.
>
>   * *REQ19*: We have an element named supportsResourcePackages to
>     define if Zip files (partial or Full) are supported. But this
>     could be achieved simply by setting a contentFormat in
>     ReadingsystemAttrributes of application/zip which is required
>     anyway. The attributes supportsResourcePackages seems redundant.
>
> *Recommendation:* Remove the attribute supportsResourcePackages
>
>   * *Service Models Section* Do we really need it? Does it make any
>     difference to a person implementing either a Service or Reading
>     System? This seems to be irrelevant in the light of the removal of
>     RequiresReturn, there is no current differentiation between
>     Lending model and Purchasing model, and many Services use both models.
>
> *Recommendation:* Remove Service Models Section from the protocol.
>
>   * *Review of Optional vs Required methods* Should
>     addContentToBookshelf be optional? For example a Library manages
>     its own content allocation and does not support the loaning of
>     Content via the Service.
>
> *Recommendation:* addContentToBookshelf be made optional
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/daisy/DAISY-Online-Refresh/issues/52>.
>

-- 
------------------------------------------------------------------------
You/Com Audiocommunicatie b.v.
Motorenweg 5k
2623CR Delft
The Netherlands
tel. : (+31)15 262 59 55
fax. : (+31)15 257 15 95
mail : jmkok@youcom.nl
http : http://www.youcom.nl
------------------------------------------------------------------------

**Comment by jmkok** [comment]
> REQ19: Review modelling of <Resources>. Currently Zip file attributes 
are duplicated; this could be modelled so a Zip type existed with Zip 
attributes, and then contained within it 1 or more resource elements.

Good idea, however this would spread out the <resource> nodes in the < 
resources> node and in one or multiple the <packages> nodes.
Might it be easier to leave all resources inside the <resources> node. 
But place the "localURI" attribute in the <package> subnodes ?
Advantages:
- fully compatible with current specification
- easier parsing and cleaner definition

example:

<resources xmlns="http://www.daisy.org/ns/daisy-online/">
     <resource mimeType="text/xml" size="123456" 
uri="https://example.com/content/get.php?a123891" localURI="package.opf"/>
     <resource mimeType="application/x-dtbncx+xml" size="123456" 
uri="https://example.com/content/get.php?a123892" localURI="nav.ncx"/>
     <resource mimeType="application/smil" size="567890"  
uri="https://example.com/content/get.php?a123893" 
localURI="chapter_1.smil"/>
     <resource mimeType="audio/mpeg" size="123456789" 
uri="https://example.com/content/get.php?a123894" localURI="chapter_1.mp3"/>
     <package uri="https://example.com/content/get.php?123" 
mimeType="application/zip" size="987">
         <resource localURI="package.opf"/>
         <resource localURI="nav.ncx"/>
         <resource localURI="chapter_1.smil"/>
     </package>
</resources>

Jelle Martijn

On 16-02-15 15:30, Claudio wrote:
>
>   * *REQ7:* Time framed content delivery We currently have methodHint
>     we propose this is renamed to accessType for better clarity,
>     (download, Stream) and priorityHint (Low, Medium, High) We believe
>     there are only 3 valid cases: Steaming/High Download/High
>     Download/Low/background This can be modelled in a single attribute
>     (eg Background, Download, and Stream) rather than the current 2.
>
> *Recommendation:* Remove priorityHint and change the accessType to 
> contain the possible values: Background, Download or Stream
>
>   * *REQ15:* Reduced function call sequence for building a Bookshelf.
>     We could merge metadata, contentMetadata with ContentItem - the
>     metadata and contentMetadata are not used by any other methods and
>     appear to have a 1-1 mandatory relationship.
>
> *Recommendation:* We merge the contentItem and contentMetadata leaving 
> the metadata element as it is.
>
>   * *REQ11:* Restrict user access to expired content (online) returnBy
>     date is specified as UTC. Should all dates be specified as UTC?
>
> *Recommendation:* lastModifiedDate, firstAccessedDate, 
> lastAccessedDate to be made in UTC
> Assumption is that the Player is able to localise Date/Time to display 
> to the user.
>
>   * *REQ31:* 302 Moved Temporarily This looks like it is only retained
>     in HTTP1.1 for compatibility reasons and should possible be using
>     307. Do we need to document the process of returning from a Temp move?
>
> *Recommendation:* Use HTTP1.1 code 307 and write guidance on process 
> to return from a temporary move.
>
>   * *REQ19:* Review modelling of |<Resources>|. Currently Zip file
>     attributes are duplicated; this could be modelled so a Zip type
>     existed with Zip attributes, and then contained within it 1 or
>     more resource elements.
>
> *Current format:*
>
> |```<resources xmlns="http://www.daisy.org/ns/daisy-online/">
>     <resource mimeType="text/xml" size="123456"
>      uri="https://example.com/content/get.php?a123891"
>      localURI="package.opf"
>      packageURI="https://example.com/content/get.php?123"
>      packageMimeType="application/zip"
>      packageSize="987"/>
>    <resource mimeType="application/x-dtbncx+xml" size="123456"
>      uri="https://example.com/content/get.php?a123892"
>      localURI="nav.ncx"
>      packageURI="https://example.com/content/get.php?123"
>      packageMimeType="application/zip"
>      packageSize="987"/>
>    <resource mimeType="application/smil" size="567890"
>      uri="https://example.com/content/get.php?a123893"
>      localURI="chapter_1.smil"
>      packageURI="https://example.com/content/get.php?123"
>      packageMimeType="application/zip"
>      packageSize="987"/>
>    <resource mimeType="audio/mpeg" size="123456789"
>      uri="https://example.com/content/get.php?a123894"
>      localURI="chapter_1.mp3"/>
>    <resource mimeType="image/jpeg" size="23456"
> </resources>```
> |
>
> *Proposed Format:*
>
> |```<resources xmlns="http://www.daisy.org/ns/daisy-online/">
>     <package URI="https://example.com/content/get.php?123"
>      MimeType="application/zip"
>      Size="987">
>         <resource mimeType="text/xml" size="123456"
>         uri="https://example.com/content/get.php?a123891"
>         localURI="package.opf"/>
>         <resource mimeType="application/x-dtbncx+xml" size="123456"
>         uri="https://example.com/content/get.php?a123892"
>         localURI="nav.ncx"/>
>       <resource mimeType="application/smil" size="567890"
>         uri="https://example.com/content/get.php?a123893"
>         localURI="chapter_1.smil"/>
>    </package>
>    <resource mimeType="audio/mpeg" size="123456789"
>      uri="https://example.com/content/get.php?a123894"
>      localURI="chapter_1.mp3"/>
> </resources>```
> |
>
> *Recommendation:* Model Packaged Resources using the proposed format.
>
>   * *REQ19*: We have an element named supportsResourcePackages to
>     define if Zip files (partial or Full) are supported. But this
>     could be achieved simply by setting a contentFormat in
>     ReadingsystemAttrributes of application/zip which is required
>     anyway. The attributes supportsResourcePackages seems redundant.
>
> *Recommendation:* Remove the attribute supportsResourcePackages
>
>   * *Service Models Section* Do we really need it? Does it make any
>     difference to a person implementing either a Service or Reading
>     System? This seems to be irrelevant in the light of the removal of
>     RequiresReturn, there is no current differentiation between
>     Lending model and Purchasing model, and many Services use both models.
>
> *Recommendation:* Remove Service Models Section from the protocol.
>
>   * *Review of Optional vs Required methods* Should
>     addContentToBookshelf be optional? For example a Library manages
>     its own content allocation and does not support the loaning of
>     Content via the Service.
>
> *Recommendation:* addContentToBookshelf be made optional
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/daisy/DAISY-Online-Refresh/issues/52>.
>

-- 
------------------------------------------------------------------------
You/Com Audiocommunicatie b.v.
Motorenweg 5k
2623CR Delft
The Netherlands
tel. : (+31)15 262 59 55
fax. : (+31)15 257 15 95
mail : jmkok@youcom.nl
http : http://www.youcom.nl
------------------------------------------------------------------------

**Comment by DaveGunn** [comment]
On REQ11: "Restrict user access to expired content (online) returnBy date is specified as UTC. Should all dates be specified as UTC?"

Just a reminder of the discussion held on 10 November when we agreed "time related communications between servers and reading systems will take place in UTC":
https://github.com/daisy/DAISY-Online-Refresh/wiki/Minutes-of-the-call-10-November-2014#revisiting-requirement-11-restrict-user-access-to-expired-content-online

**Comment by fredrikschill** [comment]
**REQ7**
YES, good idea.

**REQ15**
YES, good idea.

**REQ11**
NO, this is not needed. Just like Jelle Martijn commented, the "xs:dateTime" type is already timezone aware, so it does not matter what time zone the time is expressed in, as long as the time zone information itself is included.

**REQ31**
YES, 307 seems like a better choice.
I don't really see the need for guidance when when going back, it is meerly about not returning 307 anymore.

**REQ19**
YES, I think the suggested solution from Vision Australia is a great simplification.

I also tend to feel that Jelle Martijn's solution here is an even more clean way to do this.

However, I would like to change the name from resource to resourceRef inside the package, to avoid a type name collision. I also believe it makes sense just like Jelle Martijn did to choose the localURI to be the key between a resource and a resourceRef.

A nice feature of this solution is also that it is possible for a resource to be included in multiple packages, if a Service wishes to do so.

Thus, my suggestion would then be:

```xml
<resources xmlns="http://www.daisy.org/ns/daisy-online/">
  <resource mimeType="text/xml" size="123456"
    uri="https://example.com/content/get.php?a123891"
    localURI="package.opf"/>
  <resource mimeType="application/x-dtbncx+xml" size="123456"
    uri="https://example.com/content/get.php?a123892"
    localURI="nav.ncx"/>
  <resource mimeType="application/smil" size="567890"
    uri="https://example.com/content/get.php?a123893"
    localURI="chapter_1.smil"/>
  <resource mimeType="audio/mpeg" size="123456789"
    uri="https://example.com/content/get.php?a123894"
    localURI="chapter_1.mp3"/>
  <package uri="https://example.com/content/get.php?123"
    mimeType="application/zip" size="987"> 
    <resourceRef localURI="package.opf"/>
    <resourceRef localURI="nav.ncx"/>
    <resourceRef localURI="chapter_1.smil"/>
  </package>
</resources>
```

**REQ19**
YES, we can remove "supportsResourcePackages".

**Service Models Section**
YES, we can remove this section.

**Review of Optional vs Required methods**
YES, we can make addContentToBookshelf optional.

**Comment by DaveGunn** [comment]
All issues discussed and addressed on Working Group calls.
