### ISSUE TITLE
readingSystemAttributes: relevance of supportsResourcePackages

### ISSUE THREAD

**Issue by bvanvelsen** [daisy/DAISY-Online-Refresh#54]
I'm writing this in regard of the public review period of the new DOD protocol:

readingSystemAttributes: How useful is the supportsResourcePackages? The contentFormat can already indicate the support of zip-files for example. Then it is implied that supportsResourcePackages is true.

So why an ambiguous property which can be implied from the formats in the supportedContentFormats? 

Best regards
Bernd van Velsen
Software Developer
Pyxima

**Comment by cmontalban** [comment]
Agreed, and has been addressed in the latest internal documentation as we recieved similar feedback previously.
