### ISSUE TITLE
(guest) user authentication

### ISSUE THREAD

**Issue by bvanvelsen** [daisy/DAISY-Online-Refresh#55]
Why MUST a reading system authenticate itself, either with a user or a guest login. Why not make all or at least some methods free to call without an active session. for example, browsing a catalog -either through the dynamic menu, or by calling a getContentList directly- could be possible without having a user account. The same applies to requesting metadata for a given book and requesting resources(for example: demo's, samples or free available books)

**Comment by cmontalban** [comment]
As part of the changes to the logOn operation we combined setReadingSystemAttributes and getServiceAttributes into the logOn operation. The current design would not allow for exchange of this information out of session, we also dont see a disadvantage from logging on with standard guest credentials.

**Comment by fredrikschill** [comment]
I was discussed during the face to face meeting that it is a good idea to maintain the requirement to use the logon operation prior to other calls, to be able to exchange the capabilities between reading systemes and services.
