### ISSUE TITLE
methodHint in getContentResources request

### ISSUE THREAD

**Issue by bvanvelsen** [daisy/DAISY-Online-Refresh#56]
We have a scenario in which we download text/binary files(HTML, SMIL, NCC, etc...), but stream all non-text files(MP3). So both the streaming and download method could be an option in our scenario. 

How does the working group think we should use the methodHint?

**Comment by cmontalban** [comment]
This is a stream method, we expect some files such as the ones you describe would be fully downloaded prior to the stream operation for efficiency, the line should be drawn at "is the content available offline or be accessed directly by the client?"

**Comment by bvanvelsen** [comment]
How about a scenario where both streaming and downloading is involved? for instance. A user is downloading a book, but also starts reading(streaming) it while the content hasn't been fully downloaded yet? should you request the same contentResources twice, with a different methodHint?

**Comment by cmontalban** [comment]
We will add checksum to the response to get content resources as an optional attribute.
This will enable reading systems to establish if content files are the same in response to 2 calls with method hint stream and download.
