### ISSUE TITLE
setProgressState

### ISSUE THREAD

**Issue by bvanvelsen** [daisy/DAISY-Online-Refresh#57]
Should the setProgressState be called every time playback switches from playing to paused in a Streaming session? because this could trigger a lot of calls to the setProgressState(switching between Pause and Resume state) in case the user is streaming. This might not be interesting for a user when using a mobile data connection.

How to deal with lost connection issues? A reading device can suddenly lose connection, and the progresstate could stay in Start, or resume state, while in fact, the reading device is not online anymore...

**Comment by cmontalban** [comment]
The xml fragments being passed are actually very small and would make no difference to someone streaming content, we anticipate users wouldnt pause and reasume hundreds of times over a streaming session, and even then the fragments wouldnt ammount to more than 100kb worth of data cost.

**Comment by bvanvelsen** [comment]
Claudio, thank you for your input on this. We actually try to reduce calls between server and clients, specially in a mobile environment. Not introduce new calls. Could this then be at least be an optional call? For instance adding a boolean on readingSystemAttributes and serviceAttributes where client and server can notify each other if they support this mechanism?

Still the issue about possible connection loss remains...

**Comment by giltay** [comment]
It's not clear whether these calls are optional or required. Section 4.4.2 needs to be rewritten to fit with RFC 2119.

**Comment by cmontalban** [comment]
We will add setProgressStateRequired to the response to logOn operation to indicate if this operation must be used by a reading system.

We understand some data will be lost in the event of loss connectivity and this will be added to the next version.
