### ISSUE TITLE
unattended downloads

### ISSUE THREAD

**Issue by bvanvelsen** [daisy/DAISY-Online-Refresh#58]
Should a server be responsible or authorized to determine when content may or may not be downloaded unattended? why would the availableForAutomaticDownload ever be false? Shouldn't it be the user's or reading devices responsibility to determine if it wants or needs content for offline, online or caching purposes?

**Comment by cmontalban** [comment]
The availableForAutomaticDownload tag is intended to inform the RS that the service wants those titles to be downloaded automatically, this is to support the use of business rules for automatic downloaders from the service side.
For a RS we support the use of Low Priority Download as their way to download such content. Perhaps further clarification is needed in the documentation?

**Comment by bvanvelsen** [comment]
Thank you for the clarification. If this is the intended use of availableForAutomaticDownload, then this was not clear to me...

So if I understand it correctly, as reading system may still automatically download content unattended, if the user chooses to download all content for offline playback. But if a server expects something to be downloaded automatically by a client, then this flag should be set to true?

**Comment by fredrikschill** [comment]
We have clarified this in the latest draft revision and the term Automatic Download has also been added to section 2.
