### ISSUE TITLE
bookmarks in contentmetadata

### ISSUE THREAD

**Issue by bvanvelsen** [daisy/DAISY-Online-Refresh#59]
It might be useful to also include whether a given contentItem has bookmarks. reading devices can then use this information to determine if calling the getBookmarks operation is relevant for the current contentItem.

**Comment by cmontalban** [comment]
Great recommendation, this would reduce a call when no bookmarks or hilites are present.

**Comment by cmontalban** [comment]
We don't anticipate people will make calls for getBookmarks to the entire bookshelf and adding a solution to this problem would just reduce 1 call when getting the content.

**Comment by bvanvelsen** [comment]
Actually, we do this is in our iOS and Android apps with rich user interfaces. We want to show the user that a contentItem has bookmarks, we do this with a visual indication on the bookshelf.
