### ISSUE TITLE
Announcements: seperation between read and "safe to delete announcements"

### ISSUE THREAD

**Issue by bvanvelsen** [daisy/DAISY-Online-Refresh#60]
Could it be useful to make a seperation between read announcements and announcements which should be removed? A user might have read an announcement, but he wishes to leave it in the reader to re-read it in the future. So maybe there should also be a removeAnnouncement method? This way you could make some sort of an e-mail inbox system where you have read and unread items. and the user is explicitly responsible to delete messages

**Comment by fredrikschill** [comment]
During the face to face meeting it was decided this is an implementation issue for the device manufacturer. However, we will add to the guidance that it is important to make sure the user actually confirmed reading the announcement prior to marking it as read.
