### ISSUE TITLE
remove non-lendable content

### ISSUE THREAD

**Issue by bvanvelsen** [daisy/DAISY-Online-Refresh#61]
This is something I could not find in the specification. Is calling returnContent allowed for non-lendable content? I think it should be allowed, so users can always choose to delete content from their bookshelf.

Maybe this can even be a property in the metadata where a contentItem can be marked, to indicate it can be deleted by a user

**Comment by cmontalban** [comment]
The removal of requiresReturn means all content is now returnable.
