### ISSUE TITLE
custom server and readingdevice information

### ISSUE THREAD

**Issue by bvanvelsen** [daisy/DAISY-Online-Refresh#62]
in the metadata you have the option to include custom metadata in the "meta" tag. I think it might be useful to also include custom data in the readingsystemattributes and serviceattributes, so clients and servers can exchange custom data.

**Comment by fredrikschill** [comment]
It was decided during the face to face meeting that it will be better to identify possible missing parameters in the readingsystemattributes and serviceattributes and suggest to add those in future updates to the spec, rather than open up custom fields.
