### ISSUE TITLE
SSL should not be required because it is vulnerable

### ISSUE THREAD

**Issue by giltay** [daisy/DAISY-Online-Refresh#64]
In section 3.1, we require Reading Systems to support SSL 3.0 and TLS 1.0. Seeing as SSL v3.0 is vulnerable to attack, should we consider dropping this requirement, and adding TLS 1.1 and 1.2?

**Comment by jmkok** [comment]
I would prefer to not specify the SSL/TLS versions at all (out of scope?). The choice of supported SSL/TLS encryption schemes is up to the library and reading systems "simply" must contain at least one matching scheme. A server will negotiate the best matching encryption scheme in the SSL handshakes.
Additionally It might be that country regulation prohibit certain encryption schemes and that schemes we now deem to be safe become unsafe in due time.

**Comment by cmontalban** [comment]
We will not define the versions of security used and this will be left up to the service and the RS developers to maintain.
