### ISSUE TITLE
Vague requirement in 4.4.3

### ISSUE THREAD

**Issue by giltay** [daisy/DAISY-Online-Refresh#65]
Section 4.4.3 states (emphasis mine): "When a Reading System attempts to stream DAISY content, it **must** ensure files are downloaded in a logical order to prevent excessive calls and load on Services for downloading non required files. I.e. the Reading System will access the NCC or NCX files and by interrogating their contents determine the files that are needed to begin streaming."

Unless we are going to spell out **exactly** what a "logical order" is, that "must" needs to be a "should". Keep in mind formats other than DAISY are supported. Also, I can imagine some readers might want an OPF before downloading the NCX.

**Comment by cmontalban** [comment]
The language will be changed to should
