### ISSUE TITLE
In 4.4.5: how should RS be aware?

### ISSUE THREAD

**Issue by giltay** [daisy/DAISY-Online-Refresh#66]
The note to section 4.4.5 reads, "When synchronizing the Content, Reading Systems should be aware that Content may appear new to a Reading System may have been accessed either automatically by a Service or by another Reading System which was setup with the same User credentials."

I think this could use more formal language. How can a Reading System be aware? I think this means that Reading Systems should not depend on content lists or content status remaining the same between sessions, since the Service or other Reading Systems belonging to the User may have modified state.

**Comment by fredrikschill** [comment]
**We have applied this improvement in the following way:**
When synchronizing the Content, Reading Systems should not depend on content lists or content status remaining the same between Sessions, since the Service or other Reading Systems belonging to the User may have modified state.
