### ISSUE TITLE
4.4.5.1 language tightening

### ISSUE THREAD

**Issue by giltay** [daisy/DAISY-Online-Refresh#67]
This sentence (in 4.4.5.1, scenario 1) could be tightened up: "In this case the Service should try to return the complete list if possible, but may return it in multiple chunks if needed for performance reasons."

Strictly speaking, there are no "chunks" in the protocol. The response would be a contentList containing the first so many items. It is up to the Reading System to make subsequent calls to retrieve the erst of the list, if desired.

**Comment by cmontalban** [comment]
The wording has been changed to say: "in this case the Service should try to return the complete list if possible, but may return it in partial lists if needed for performance reasons."
