### ISSUE TITLE
4.5.2 awkwardness in viewpoint

### ISSUE THREAD

**Issue by giltay** [daisy/DAISY-Online-Refresh#68]
The third paragraph of 4.5.2 reads, "If a Reading System calls markAnnouncementsAsRead, and a Service returns false, then the announcement has already been marked as read. If a Service returns an invalidParameter Fault, then the announcement identifier does not exist on the Service."

This is written as how a Reading System should interpret results from a call. It should be rewritten to indicate that these are the value the Service must return in these situations.

This was inherited from DODP 1.0, so it should be made an erratum for that version.

**Comment by fredrikschill** [comment]
**This good suggestion has been added in this way:**
If a Reading System calls markAnnouncementsAsRead, and a Service returns false, then the announcement has already been marked as read. If an announcement identifier does not exist on the Service, the Service must return an invalidParameter Fault.
