### ISSUE TITLE
STOP mode needs definition

### ISSUE THREAD

**Issue by giltay** [daisy/DAISY-Online-Refresh#69]
In 4.5.3, there are two references to "STOP mode". There does not appear to be a definition for this term, nor does it appear anywhere else in the document. In one case, it refers to a Reading System, in the other, to the User! I know it makes intuitive sense, but the formatting makes it look like a special term.

The term "stopped" may not even have a meaning in the case of text-only content being read by a sighted user. Better to use something along the lines of "the next time the Reading System is not rendering Content".

**Comment by cmontalban** [comment]
We have changes the wording from STOP mode to idle. the section has been rewritten also to remove other references.
