### ISSUE TITLE
serviceAnnouncements pull frequency

### ISSUE THREAD

**Issue by bvanvelsen** [daisy/DAISY-Online-Refresh#70]
Service announcements are an optional service, but the announcementsPullFrequency in the serviceAttributes is required.

I propose to make the attribute "announcementsPullFrequency" also optional.

**Comment by fredrikschill** [comment]
During the face to face meeting it was decided to keep this parameter required.
We will also define the value 0 to indicate only to pull at logon and not repeatadly.
