### ISSUE TITLE
supportsRestrictedDownload vs supportsDownload

### ISSUE THREAD

**Issue by bvanvelsen** [daisy/DAISY-Online-Refresh#71]
In the ElementsReference, where supportsRestrictedDownload is explained, I read the following:

"supportsRestrictedDownload must not be false if supportsDownload is false."

So basically -if I understand it correctly-, this means "If supportsDownload is false, supportRestrictedDownload must be true". Why is this? Can't the service decide that any given contentItem must not be allowed to downloaded by a reading system? I would expect that some content is only available for streaming.

**Comment by cmontalban** [comment]
This has been handled in the new version of the protocol, the system now uses values with valid combinations only.
