### ISSUE TITLE
supportsRestrictedDownload on serviceAttributes

### ISSUE THREAD

**Issue by bvanvelsen** [daisy/DAISY-Online-Refresh#72]
Is this required on the ServiceAttributes? Basically a service does not download at all. If there is an attribute in the serviceAttributes then I would expect it to be called "requiresRestrictDownloading", but even that might be confusing, because some contentItems may be downloaded to public location on a reading system.

Maybe it would make more sense to remove this atribute completly from the serviceAttributes and just inform the user in the metadata of a contentItem if it must be downloaded to a restricted location.

**Comment by fredrikschill** [comment]
This has been removed in the last draft version.
