### ISSUE TITLE
supportedRestrictedDownload, add note specification

### ISSUE THREAD

**Issue by bvanvelsen** [daisy/DAISY-Online-Refresh#73]
I propose to add a note similar as the one on the returnContent operation, to inform implementers of the specification that even if the device supports restricted downloading, that there are always possibilities and "creative users" who may or could break this system and get a hold of a copy of content on restricted locations

**Comment by cmontalban** [comment]
We have specified that PDTB2 is the only real way to protect content and other methods cannot be guaranteed, we don't think adding notes to the possible vulnerability of each individual operation would be helpful.
