### ISSUE TITLE
contentlist sorting

### ISSUE THREAD

**Issue by bvanvelsen** [daisy/DAISY-Online-Refresh#74]
- add optional option to indicate if sorting should be ascending or descending
- remove restriction that only the proposed values are allowed. it should be possible to add custom sorting, or at least more options(for instance the metadata field like: narrator, language, date,)

**Comment by cmontalban** [comment]
Given the changes to the changes to the getContentList operation we considered the option of the player requesting a sorted list redundant.

Content is sorted at the service end and provided to the RS in the preferred order for the service provider, the RS is then able to re-sort the list internally as it sees fit and render it to the user.
