### ISSUE TITLE
Is returnBy a contract now?

### ISSUE THREAD

**Issue by giltay** [daisy/DAISY-Online-Refresh#77]
In 1.0, we left returnBy a matter between the Service Provider and the User, with no enforcement by the protocol. We explicitly said so in a couple of places, which remain the same in the current draft.

In 2.0, it's now a requirement that the Reading System honours the returnBy value. Should the language be changed or removed in the following sections?

In 4.1.1.3: "This protocol does not require the enforcement of these methods on the Reading System."

In 6.5: "This attribute does not constitute a contract."

**Comment by cmontalban** [comment]
Any kind of contract that exists is between the library and the person, the reading system is acting as an intermediary between the library and the user and supports the policies that are in place.

We have removed the wording in 6.5 and reworded 4.1.1.3 to be in line with the rest of the spec.
