### ISSUE TITLE
5.1.4: fuzzy language

### ISSUE THREAD

**Issue by giltay** [daisy/DAISY-Online-Refresh#78]
Section 5.1.4 states, "If the intention of what to do with the content changes (for example methodHint changes from download to stream), the getContentResources must be re-called to ensure the Service is aware of what the content is being accessed for."

"Intention" and "aware" are not well-defined for electronic devices. I suggest something like:

"If the Reading System changes from downloading to streaming or vice-versa, it must call getContentResources again with methodHint containing the new value. Resources provided by the previous call are not guaranteed to be available following this."

**Comment by fredrikschill** [comment]
**The text has been altered to:**
If a Reading System starts a new process, then getContentResources must be called again with a new valid accessType such as DOWNLOAD or STREAM.
