### ISSUE TITLE
Remove last paragraph from 1. Introduction?

### ISSUE THREAD

**Issue by fredrikschill** [daisy/DAISY-Online-Refresh#80]
### Did we decide to remove this paragraph?

**Last paragraph in 1. Introduction:**
One feature of the protocol is the discovery of DAISY Online Delivery services. The DAISY Consortium has developed a system and specification for tracking and locating online services.

**Comment by fredrikschill** [comment]
We had a long discussion around this but I cannot remember what we finally decided on.

**Comment by DaveGunn** [comment]
I think this was also highlighted by Andrew, and from memory I believe we concluded that the feature was very much part of the specification, but did not need to be an isolated highlight in the introduction - so I believe we agreed to remove it. Unfortunately my notes didn’t capture this decision clearly.

**Comment by fredrikschill** [comment]
On the phone call 2015-03-09, we decided to remove this paragraph.
