### ISSUE TITLE
re-open issue: Bookmarks in metadata

### ISSUE THREAD

**Issue by bvanvelsen** [daisy/DAISY-Online-Refresh#83]
Since I cannot re-open issues, I'm creating this new one. I would like to draw attention again to this issue:
https://github.com/daisy/DAISY-Online-Refresh/issues/59

The last comment by @cmontalban was that it was not anticipated that reading systems would call the bookmarks for the entire bookshelf.

Actually, we do this is in our iOS and Android apps with rich user interfaces. We want to show the user that a contentItem has bookmarks, we do this with a visual indication on the bookshelf. But since there is no standard way in achieving this easily, we need to call the entire bookmark list when building the bookshelf. A simple boolean value in the metadata can make these calls redundant. This will hugely improve our apps performance and data usage.

Also for the same reason we will also need to know whether or not there is a lastmark: to indicate if a book has been read or not

**Comment by PerSennels** [comment]
In our app, developed by Pyxima, we also have indication for each book on the bookshelf whether it contains a bookmark or not.
I don't think this is a very important thing for our users, and if we have to choose between efficient updating of bookshelves and display of bookmark status, I certainly prefer the first one.
Lastmark is much more important, but that is taken care of by the version 2.0..

**Comment by DaveGunn** [comment]
We discussed this issue again on the call this week, you can read the minutes of the discussion here: https://github.com/daisy/DAISY-Online-Refresh/wiki/Minutes-of-the-call-16-March-2015#issue-83-bookmarks-in-metadata

**Comment by cmontalban** [comment]
We introduced a new boolean attribute on Content Item called hasBookmarks, this will inform the RS if the title has Bookmarks or Hilites.
