### ISSUE TITLE
Topics on Guidance

### ISSUE THREAD

**Issue by fredrikschill** [daisy/DAISY-Online-Refresh#84]
### Topics on Guidance

  * Automatic Reading System Configuration (Jelle Martijn working on first draft for Service Discovery and Reading System Configuration)
    * Service Discovery
    * Reading System Configuration
  * Content Retrieval Sequence (Fredrik working on first draft)
  * Downloading and Streaming of Content (Fredrik working on first draft)
  * Service Announcements (Claudio working on first draft)
  * Bookmarks (Claudio working on first draft)
  * Dynamic Menus (Shinano Kenshi working on first draft of all Dynamic Menu guidance)
    * General Usage
    * Search
    * Content Discovery
    * User History
  * Sample Workflow (Per working on first draft)

**Comment by DaveGunn** [comment]
These topics have now been incorporated in the guidance documentation
