### ISSUE TITLE
Examples in the specification

### ISSUE THREAD

**Issue by PerSennels** [daisy/DAISY-Online-Refresh#89]
I think it would be very helpful for the reader if we are able to give at least one example of typical use, for each of the operations described in the sections
5.1 Required Operations
5.2 Optional Operations

And similar for
Chapter 6. Type reference
There are some very good examples for many of the types defined in this chapter, but there should be one example for each type.

**Comment by DaveGunn** [comment]
Examples have been included in the specification and the guidance.
