### ISSUE TITLE
Element Reference as a separate chapter

### ISSUE THREAD

**Issue by PerSennels** [daisy/DAISY-Online-Refresh#90]
Currently the information about all the elements is a seubsection (6.17) til Chapter 6. Type Reference.
It should be placed in a separate chapter.
And perhaps alle the elements should be described in separate sections:
7.1 accessConfig
7.2 accessPermission
7.3 additionalTransferProtocols
etc

**Comment by fredrikschill** [comment]
This will come in the next draft.
