### ISSUE TITLE
logOn by device

### ISSUE THREAD

**Issue by jmkok** [daisy/DAISY-Online-Refresh#91]
In the meeting of this morning I suggested an idea as an alternative to issue #86.
The primary reason for this is my worry for the complexity involved in getCredentials(). This might result in reading services not implementing such a function at all.
The examples below are merely meant to indicate the idea of this procedure

In short:
Instead of requesting the username/password, the device directly logs on using its signed serial number.

It uses the same private/public key infrastructure as the getCredentials call.

A logon request could look like:

```xml
<logon>
    <serial>123456-ABCDEF</serial>
    <manufacturer>foo</manufacturer>
    <signature>VEhJU19JU19USEVfU0lHTkFUVVJFIQ==</signature>
</logon>
```

How is this safe ?
The signature can only be created by devices which have access to the private key
The signature can be verified by anyone

What are the benefits compared to getCredentials():
- a device logon does not have to know the password so it cannot leak or lose it
- it does not need to be stored unencryped on the server - or it cannot be server to the player or multiple players)
- it may simply be changed
- a device can be "detached" from a user account remotely

Disadvantages:
- unspecified "signature" method ([xmldsig](http://www.w3.org/TR/xmldsig-core/)?)
- very last minute change...
- not yet forseen issues...

**Comment by DaveGunn** [comment]
Discussed on the call [27 April 2015](https://github.com/daisy/DAISY-Online-Refresh/wiki/Minutes-of-the-call-27-April-2015#issue-91-logon-by-device91) and as agreed moved to the [2.1 udpate list](https://github.com/daisy/DAISY-Online-Refresh/wiki/Suggestions-for-DODP-2.1-updates)
