### ISSUE TITLE
Dynamic Menu Update

### ISSUE THREAD

**Issue by cmontalban** [daisy/DAISY-Online-Refresh#96]
Added defaultValue as an optional attribute to InputQuestion type.

Updated the content model for the contentItem element and added an optional multipleChoiceQuestion child element. This can be used to support contentItem menus within dynamic menus.

Updated the content model for the questions type to allow for optional labels also together with questions and content lists.

**Comment by jmkok** [comment]
See comments in issue #95

**Comment by fredrikschill** [comment]
This has been inplemented in draft 37.
