### ISSUE TITLE
Draft Guidance getUserCredentials comments

### ISSUE THREAD

**Issue by MWKlarer** [daisy/DAISY-Online-Refresh#97]
I don't fully understand encryption programming, however my initial thoughts are that this proposal is attempting to 'reinvent the wheel.'

I think if you restrict this type of transaction over https, you do not need to program your own key exchanges. 

You will not restrict yourself to text limits, as well implemented https servers and clients handle this automatically.

**Comment by DaveGunn** [comment]
We discussed this on the call this week, and the link below to the minutes provides more detailed information which you might find useful. In summary HTTPS and encryption are performing two very separate tasks. The encryption is required to authenticate a reading system on first use and remotely configure it with user credentials for subsequent use. Once established the reading system can use HTTPS to securely communication those user credentials back to the service. 

On the call everybody agreed there remained a need for both encryption and HTTPS, but your comment did identify the need to clarify this distinction in the guidance, which will be reflected in the next update.
Thanks for raising this.
Dave

https://github.com/daisy/DAISY-Online-Refresh/wiki/Minutes-of-the-call-22-June-2015#issue-97-comment-on-draft-guidance-getusercredentials
